[package]
name = "cait"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
sailfish = "0.7.0"
axum = "0.6.18"
tokio = { version = "1.29.1", features = ["full"] }
lightningcss = "1.0.0-alpha.44"
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
